version: '3.8'
services:
  onesub:
    image: wiziscool/onesub:latest
    container_name: onesub
    ports:
      - "3000:3000"  # 将容器的3000端口映射到主机
    environment:
      - GITHUB_CLIENT_ID=your_client_id  # 替换为您的GitHub OAuth应用的Client ID
      - GITHUB_CLIENT_SECRET=your_client_secret  # 替换为您的GitHub OAuth应用的Client Secret
      - BASE_URL=http://localhost:3000  # 替换为您的服务地址
    restart: always
    volumes:
      - ./database:/app/database  # 将主机的 database 目录挂载到容器中
